version: '3.3'
services:
  app:
    container_name: tsks-web-storybook
    build:
      context: .
      dockerfile: Dockerfile.storybook
    ports:
      - '6006:6006'
    volumes:
      - ./:/app/
      - /app/node_modules
