version: '3.3'
services:
  app:
    container_name: tsks-web-app
    image: tsks-web-app
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/
      - /app/node_modules
    #env_file:
    #  - .env.dev
    command: yarn dev
