version: '3.3'
name: tsks-web
services:
  app:
    container_name: tsks-web-app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - /app/node_modules
    env_file:
      - .env.dev
  test:
    container_name: tsks-web-test
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/test/
      - /test/node_modules
    env_file:
      - .env.dev
    depends_on:
      - app