version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  dbdata:
