version: '3.8'
services:
  db:
    container_name: tsks-api-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"
  db-migration:
    container_name: tsks-api-db-migration
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rake db:prepare
    depends_on:
      - db
    volumes:
      - .:/app
  app:
    container_name: tsks-api-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - db-migration
    volumes:
     - .:/app
    ports:
      - 5000:5000
    env_file:
      - .env.dev