version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"
  db-migration:
    build: .
    command: bundle exec rake db:prepare
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    volumes:
      - .:/app
  svc:
    build: .
    environment:
      RAILS_ENV: development
    depends_on:
      - db
      - db-migration
    volumes:
     - .:/app
    ports:
      - 5000:5000
