version: '3.3'
name: tsks-web
services:
  lint:
    container_name: tsks-web-lint
    build: 
      context: .
      dockerfile: Dockerfile.lint
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - /app/node_modules
    env_file:
      - .env.dev