version: '3.3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - /app/node_modules
    env_file:
      - .env.dev
    networks:
      default:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/test/
      - /test/node_modules
    env_file:
      - .env.dev
    networks:
      default:
    depends_on:
      - web
networks:
  default:

