version: '3.3'
name: tsks-web
services:
  app:
    container_name: tsks-web-app
    image: tsks-web-app
    ports:
      - '80:3000'
      - '6006:6006'
    volumes:
      - ../:/app/
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/v1
      - NEXT_PUBLIC_USER_LOCAL_STORAGE_KEY=@tsks-user
      - NEXT_PUBLIC_AUTH_TOKEN_LOCAL_STORAGE_KEY=@tsks-auth-token
    command: yarn dev
